-- Добавление напитков, соусов и салатов в меню
-- Выполните этот скрипт в Supabase SQL Editor

-- ============================================
-- НАПИТКИ (Бутылки 0.5л)
-- ============================================

INSERT INTO menu (
    id,
    name,
    category,
    sub_category,
    sub_category_en,
    sub_category_sr,
    title,
    title_en,
    title_sr,
    description,
    description_en,
    description_sr,
    price,
    image_url,
    weight,
    calories,
    ingredients,
    rating,
    available,
    preparation_time,
    allergens
) VALUES
-- Кола
(
    gen_random_uuid(),
    'Coca-Cola 0.5л',
    'Напитки',
    'Газированные напитки',
    'Soft Drinks',
    'Bezalkoholna pića',
    'Coca-Cola 0.5л',
    'Coca-Cola 0.5L',
    'Coca-Cola 0.5L',
    'Классическая кока-кола в бутылке 0.5л',
    'Classic Coca-Cola in 0.5L bottle',
    'Klasična Coca-Cola u boci od 0.5L',
    150,
    'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    '500мл',
    210,
    ARRAY['Вода', 'Сахар', 'Диоксид углерода', 'Краситель', 'Кофеин'],
    4.5,
    true,
    1,
    NULL
),

-- Спрайт
(
    gen_random_uuid(),
    'Sprite 0.5л',
    'Напитки',
    'Газированные напитки',
    'Soft Drinks',
    'Bezalkoholna pića',
    'Sprite 0.5л',
    'Sprite 0.5L',
    'Sprite 0.5L',
    'Освежающий лимонад в бутылке 0.5л',
    'Refreshing lemon-lime soda in 0.5L bottle',
    'Osvežavajući limunad u boci od 0.5L',
    150,
    'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=400',
    '500мл',
    180,
    ARRAY['Вода', 'Сахар', 'Диоксид углерода', 'Лимонная кислота'],
    4.5,
    true,
    1,
    NULL
),

-- Фанта
(
    gen_random_uuid(),
    'Fanta Orange 0.5л',
    'Напитки',
    'Газированные напитки',
    'Soft Drinks',
    'Bezalkoholna pića',
    'Fanta Orange 0.5л',
    'Fanta Orange 0.5L',
    'Fanta Orange 0.5L',
    'Апельсиновая газировка в бутылке 0.5л',
    'Orange soda in 0.5L bottle',
    'Narandžasti napitak u boci od 0.5L',
    150,
    'https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=400',
    '500мл',
    200,
    ARRAY['Вода', 'Сахар', 'Апельсиновый сок', 'Диоксид углерода'],
    4.5,
    true,
    1,
    NULL
),

-- Вода негазированная
(
    gen_random_uuid(),
    'Вода негазированная 0.5л',
    'Напитки',
    'Вода',
    'Water',
    'Voda',
    'Вода негазированная 0.5л',
    'Still Water 0.5L',
    'Negazirana voda 0.5L',
    'Чистая питьевая вода без газа',
    'Pure still drinking water',
    'Čista negazirana voda za piće',
    100,
    'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400',
    '500мл',
    0,
    ARRAY['Вода'],
    5.0,
    true,
    1,
    NULL
),

-- Вода газированная
(
    gen_random_uuid(),
    'Вода газированная 0.5л',
    'Напитки',
    'Вода',
    'Water',
    'Voda',
    'Вода газированная 0.5л',
    'Sparkling Water 0.5L',
    'Gazirana voda 0.5L',
    'Освежающая газированная вода',
    'Refreshing sparkling water',
    'Osvežavajuća gazirana voda',
    120,
    'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400',
    '500мл',
    0,
    ARRAY['Вода', 'Диоксид углерода'],
    5.0,
    true,
    1,
    NULL
),

-- Апельсиновый сок
(
    gen_random_uuid(),
    'Апельсиновый сок 0.5л',
    'Напитки',
    'Соки',
    'Juices',
    'Sokovi',
    'Апельсиновый сок 0.5л',
    'Orange Juice 0.5L',
    'Sok od narandže 0.5L',
    '100% натуральный апельсиновый сок',
    '100% natural orange juice',
    '100% prirodni sok od narandže',
    200,
    'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    '500мл',
    220,
    ARRAY['Апельсиновый сок'],
    4.8,
    true,
    1,
    NULL
),

-- Яблочный сок
(
    gen_random_uuid(),
    'Яблочный сок 0.5л',
    'Напитки',
    'Соки',
    'Juices',
    'Sokovi',
    'Яблочный сок 0.5л',
    'Apple Juice 0.5L',
    'Sok od jabuke 0.5L',
    '100% натуральный яблочный сок',
    '100% natural apple juice',
    '100% prirodni sok od jabuke',
    200,
    'https://images.unsplash.com/photo-1568471173238-64ed8e7e9954?w=400',
    '500мл',
    230,
    ARRAY['Яблочный сок'],
    4.8,
    true,
    1,
    NULL
),

-- Вишнёвый сок
(
    gen_random_uuid(),
    'Вишнёвый сок 0.5л',
    'Напитки',
    'Соки',
    'Juices',
    'Sokovi',
    'Вишнёвый сок 0.5л',
    'Cherry Juice 0.5L',
    'Sok od višnje 0.5L',
    '100% натуральный вишнёвый сок',
    '100% natural cherry juice',
    '100% prirodni sok od višnje',
    220,
    'https://images.unsplash.com/photo-1610889556528-6655c8348494?w=400',
    '500мл',
    250,
    ARRAY['Вишнёвый сок'],
    4.7,
    true,
    1,
    NULL
);

-- ============================================
-- СОУСЫ
-- ============================================

INSERT INTO menu (
    id,
    name,
    category,
    sub_category,
    sub_category_en,
    sub_category_sr,
    title,
    title_en,
    title_sr,
    description,
    description_en,
    description_sr,
    price,
    image_url,
    weight,
    calories,
    ingredients,
    rating,
    available,
    preparation_time,
    allergens
) VALUES
-- Кетчуп
(
    gen_random_uuid(),
    'Кетчуп',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Кетчуп',
    'Ketchup',
    'Kečap',
    'Классический томатный кетчуп',
    'Classic tomato ketchup',
    'Klasični kečap od paradajza',
    50,
    'https://images.unsplash.com/photo-1528790808434-cfc3a9d75c5d?w=400',
    '50г',
    60,
    ARRAY['Томаты', 'Сахар', 'Уксус', 'Соль', 'Специи'],
    4.5,
    true,
    1,
    NULL
),

-- Майонез
(
    gen_random_uuid(),
    'Майонез',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Майонез',
    'Mayonnaise',
    'Majonez',
    'Классический майонез',
    'Classic mayonnaise',
    'Klasični majonez',
    50,
    'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400',
    '50г',
    150,
    ARRAY['Яйца', 'Растительное масло', 'Уксус', 'Горчица'],
    4.5,
    true,
    1,
    ARRAY['Яйца', 'Горчица']
),

-- Чесночный соус
(
    gen_random_uuid(),
    'Чесночный соус',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Чесночный соус',
    'Garlic Sauce',
    'Beli luk sos',
    'Сливочный соус с чесноком',
    'Creamy garlic sauce',
    'Kremasti sos sa belim lukom',
    70,
    'https://images.unsplash.com/photo-1635611426280-6d0a875cd912?w=400',
    '50г',
    120,
    ARRAY['Сметана', 'Чеснок', 'Майонез', 'Специи'],
    4.7,
    true,
    2,
    ARRAY['Молоко', 'Яйца']
),

-- Барбекю
(
    gen_random_uuid(),
    'Соус Барбекю',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Соус Барбекю',
    'BBQ Sauce',
    'BBQ sos',
    'Пикантный соус для мяса',
    'Spicy meat sauce',
    'Začinjeni sos za meso',
    70,
    'https://images.unsplash.com/photo-1617465971531-0b2220d2f75e?w=400',
    '50г',
    80,
    ARRAY['Томаты', 'Уксус', 'Специи', 'Коричневый сахар'],
    4.6,
    true,
    1,
    NULL
),

-- Сырный соус
(
    gen_random_uuid(),
    'Сырный соус',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Сырный соус',
    'Cheese Sauce',
    'Sir sos',
    'Нежный соус с сыром чеддер',
    'Creamy cheddar cheese sauce',
    'Kremasti sos sa čedar sirom',
    80,
    'https://images.unsplash.com/photo-1619740455993-a42cca7b9242?w=400',
    '50г',
    140,
    ARRAY['Сыр Чеддер', 'Сливки', 'Молоко', 'Специи'],
    4.8,
    true,
    2,
    ARRAY['Молоко']
),

-- Острый соус
(
    gen_random_uuid(),
    'Острый соус',
    'Соусы',
    'Соусы',
    'Sauces',
    'Sosovi',
    'Острый соус',
    'Hot Sauce',
    'Ljuti sos',
    'Острый перечный соус',
    'Spicy chili sauce',
    'Ljuti sos od čilija',
    60,
    'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    '50г',
    40,
    ARRAY['Перец чили', 'Уксус', 'Чеснок', 'Соль'],
    4.4,
    true,
    1,
    NULL
);

-- ============================================
-- САЛАТЫ
-- ============================================

INSERT INTO menu (
    id,
    name,
    category,
    sub_category,
    sub_category_en,
    sub_category_sr,
    title,
    title_en,
    title_sr,
    description,
    description_en,
    description_sr,
    price,
    image_url,
    weight,
    calories,
    ingredients,
    rating,
    available,
    preparation_time,
    allergens
) VALUES
-- Цезарь
(
    gen_random_uuid(),
    'Салат Цезарь',
    'Салаты',
    'Салаты',
    'Salads',
    'Salate',
    'Салат Цезарь',
    'Caesar Salad',
    'Cezar salata',
    'Классический салат с курицей, сыром пармезан и соусом Цезарь',
    'Classic salad with chicken, parmesan cheese and Caesar dressing',
    'Klasična salata sa piletinom, parmezan sirom i Cezar dresingom',
    450,
    'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    '300г',
    380,
    ARRAY['Салат Романо', 'Куриное филе', 'Сыр Пармезан', 'Сухарики', 'Соус Цезарь'],
    4.8,
    true,
    10,
    ARRAY['Глютен', 'Молоко', 'Яйца', 'Рыба']
),

-- Греческий
(
    gen_random_uuid(),
    'Греческий салат',
    'Салаты',
    'Салаты',
    'Salads',
    'Salate',
    'Греческий салат',
    'Greek Salad',
    'Grčka salata',
    'Свежие овощи с сыром фета и оливками',
    'Fresh vegetables with feta cheese and olives',
    'Sveže povrće sa feta sirom i maslinama',
    400,
    'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    '280г',
    280,
    ARRAY['Помидоры', 'Огурцы', 'Болгарский перец', 'Красный лук', 'Сыр Фета', 'Оливки', 'Оливковое масло'],
    4.7,
    true,
    8,
    ARRAY['Молоко']
),

-- Овощной
(
    gen_random_uuid(),
    'Овощной салат',
    'Салаты',
    'Салаты',
    'Salads',
    'Salate',
    'Овощной салат',
    'Vegetable Salad',
    'Salata od povrća',
    'Микс свежих сезонных овощей',
    'Mix of fresh seasonal vegetables',
    'Miks svežeg sezonskog povrća',
    320,
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    '250г',
    150,
    ARRAY['Салат', 'Помидоры', 'Огурцы', 'Морковь', 'Капуста', 'Оливковое масло'],
    4.5,
    true,
    7,
    NULL
),

-- Капрезе
(
    gen_random_uuid(),
    'Салат Капрезе',
    'Салаты',
    'Салаты',
    'Salads',
    'Salate',
    'Салат Капрезе',
    'Caprese Salad',
    'Kapreze salata',
    'Моцарелла, томаты и базилик с бальзамическим уксусом',
    'Mozzarella, tomatoes and basil with balsamic vinegar',
    'Mocarela, paradajz i bosiljak sa balzamik sirćetom',
    480,
    'https://images.unsplash.com/photo-1592417817038-d13e4d23e0c4?w=400',
    '270г',
    320,
    ARRAY['Моцарелла', 'Томаты', 'Базилик', 'Оливковое масло', 'Бальзамический уксус'],
    4.9,
    true,
    8,
    ARRAY['Молоко']
);

-- Проверка: сколько блюд добавлено
SELECT
    category,
    COUNT(*) as count
FROM menu
GROUP BY category
ORDER BY category;
